services:
  # python web service
  - type: web
    name: gpt4free
    runtime: python
    rootDir: .
    autoDeploy: false
    repo: https://github.com/cherylh111/gpt4free # optional
    region: singapore       # optional (defaults to oregon)
    plan: free              # optional (defaults to starter instance type)
    branch: main            # optional (defaults to master)
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m interference.app
    envVars:
      - key: PYTHON_VERSION # 这里的 python version 是用来指定 Python 版本的，比如这里我用的是 3.11.4。
        value: 3.11.4
